spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001      #注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password: li1990521
    dbcp2:
      min-idle: 5                                       # 数据库连接池的最小维持连接数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接获取的最大超时时间
  cloud:
    inetutils:
      ignored-interfaces:
      - VMware Virtual Ethernet Adapter for VMnet1
      - VMware Virtual Ethernet Adapter for VMnet8

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.lihang.springcloud.entities # 所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                   # mybatis映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka        #单机版
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com             # 自定义服务名称信息
    prefer-ip-address: true                             # 访问路径可以显示IP地址

info: 
  app.name: lihang-microservicecloud
  company.name: 李航
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001      #注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: li1990521
    dbcp2:
      min-idle: 5                                       # 数据库连接池的最小维持连接数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接获取的最大超时时间
  cloud:
    inetutils:
      ignored-interfaces:
      - VMware Virtual Ethernet Adapter for VMnet1
      - VMware Virtual Ethernet Adapter for VMnet8

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.lihang.springcloud.entities # 所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                   # mybatis映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka        #单机版
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com             # 自定义服务名称信息
    prefer-ip-address: true                             # 访问路径可以显示IP地址

info: 
  app.name: lihang-microservicecloud
  company.name: 李航
  build.artifactId: $project.artifactId$
  build.version: $project.version$